# Header

menu:
  主页: /
  # 关于: /about

# SubNav
subnav:
  # github: "#"
  # weibo: "#"
  # rss: "#"
  # zhihu: "#"
  mail: "mailto:hbrwang@outlook.com"
  weixin: "/img/weixin_qr.jpg"
  # qq: "/img/qq_qr.jpg"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: 更多
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: "展开全文"
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
# 打赏wording
reward_wording: "感谢您的支持"
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: "/img/alipay_rec.jpg"
# 微信二维码图片地址
weixin: "/img/weixin_rec.jpg"

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: false
# 目录为空时的提示
toc_empty_wording: "不存在目录"

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: "50af574591e736cb95aee409f714ec91"
google_analytics: ""
favicon: /img/avatar.png

#你的头像url
avatar: /img/avatar.png

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: "hbrwang" #你的 GitHub ID
gitment_repo: "issues" #存储评论的 repo
gitment_oauth:
  client_id: "e1c8f248da951d7ff6b5" #client ID
  client_secret: "343cc670243006e34214aa7e8ccf459612ff1b2b" #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: "#4d4d4d"
  # 右滑板块背景
  slider: "linear-gradient(200deg,#7b5d5f,#ba8f6c)"

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: "搜索"
  friends: false
  # aboutme: "关于"

friends:
  友情链接1: http://localhost:4000/
  友情链接2: http://localhost:4000/
  友情链接3: http://localhost:4000/
  友情链接4: http://localhost:4000/
  友情链接5: http://localhost:4000/
  友情链接6: http://localhost:4000/

aboutme: <div style="display:flex;flex-direction:column;align-items:center;"><span>爱生活，爱编程</span><span>的</span><span>95程序员大叔</span><span style="align-self:flex-end;margin-top:20px;"><a href="https://blog.hubery.wang/about">更多</a></span></div>
